
FROM node:18-alpine
WORKDIR /app

ARG REACT_APP_FRONTEND_PORT
ENV REACT_APP_FRONTEND_PORT=$REACT_APP_FRONTEND_PORT

COPY src/frontend/package*.json ./
RUN npm install

COPY src/frontend/ ./

COPY src/frontend/.env .env

EXPOSE $REACT_APP_FRONTEND_PORT
CMD ["npm", "start"]